name: Count Lines, Comments, and Test Lines

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  count-lines:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cloc

    - name: Count lines, comments, and test lines
      run: |
        echo "Analyzing the project..."
        
        # Count total lines and comments
        cloc . --json > cloc_output.json
        TOTAL_LINES=$(jq '.SUM.code' cloc_output.json)
        TOTAL_COMMENTS=$(jq '.SUM.comment' cloc_output.json)

        # Count lines in test files
        cloc . --json --match-d=".*[Tt]ests?.*" --match-f=".*[Tt]ests?.*" > cloc_tests_output.json
        TEST_LINES=$(jq '.SUM.code' cloc_tests_output.json)

        # Output results
        echo "Total lines of code: $TOTAL_LINES"
        echo "Total comments: $TOTAL_COMMENTS"
        echo "Total lines in test files: $TEST_LINES"
